version: '3.6'

services:
    nanosbackend:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/nanosbackend
        ports:
            - '3000:3000'
        volumes:
            - ./:/usr/src/nanosbackend
